## azure-pipelines.yml
stages:

- stage: one
  jobs:
  - job: A
    steps:
    - script: |
       echo "##vso[task.setvariable variable=skipsubsequent;isOutput=true]true"
      name: skipstep

- stage: two
  jobs:
  - job: B
    variables:
      - name: skipMe
        value: $[ stageDependencies.one.A.outputs['skipstep.skipsubsequent'] ]
    steps:
    - script: |
          echo 'Hello inline version'
          echo $(skipMe) 
