
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  var1: 10
  var2: 20

steps:
- checkout: self

- task: Bash@3
  name: Fetch_Version
  displayName: 'Build version'
  inputs:
    targetType: 'inline'
    script: |
      pwd
      ls
      LAST_LINE=1.0.0
      echo "last_line : $LAST_LINE"
      echo "##vso[task.setvariable variable=last_line]$LAST_LINE"
      echo "last_line-2 : $last_line" 
    

- script: |
    echo " Updated lastline : $(last_line)"


