stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - script: |
        echo "##vso[task.setvariable variable=skipStage2;isOutput=true]true"
      name: SetVariable

- stage: Stage2
  dependsOn: Stage1
  condition: and(succeeded(), eq(dependencies.Stage1.outputs['Job1.SetVariable.skipStage2'], 'false'))
  jobs:
  - job: Job2
    steps:
    - script: echo "This is Stage 2"
