trigger: none


pool:
  vmImage: 'ubuntu-latest'

#variables:
#  resource_type: Kubernetes_Cluster

jobs:
- job: A
  steps:
  - script: |
      resource_type="Kubernetes_Cluster"
      echo "##vso[task.setvariable variable=resource_type;isOutput=true;]$resource_type"
      echo "variable value is $(resource_type)"
      echo "Resource type is $(resource_type)"
    displayName: "Print Resource Type"
  # Your other steps here

- job: B
  dependsOn: A 
  variables:
    resource_type: $[ dependencies.A.outputs['setVariable.resource_type'] ]
  steps:
  - script: |
      echo "Resource type is $(resource_type)"
      echo "Step 1"
    displayName: "Step 1"
    name: "step_1"
    condition: eq(variables['resource_type'], 'Kubernetes_Cluster')
  - script: |
      echo "Step 2"
    displayName: "Step 2"
    name: "step_2"
    condition: ne(variables['resource_type'], 'Kubernetes_Cluster')

