trigger:
- main

stages:
- stage: ExampleStage
  displayName: "Example Stage"
  variables:
    stageVariable: 3  # Set your stage variable value here

  jobs:
  - job: Job0
    displayName: "Job 0"
    condition: and(succeeded(), eq(variables['stageVariable'], 0))  # Runs only if stageVariable is 0
    steps:
    - script: |
        echo "Running Job 0"
        stageVariable=1
        echo "##vso[task.setvariable variable=stageVariable]$stageVariable"
  
  - job: Job1
    displayName: "Job 1"
    condition: and(succeeded(), or(eq(variables['stageVariable'], 0), eq(variables['stageVariable'], 1)))  # Runs only if stageVariable is 1
    steps:
    - script: |
        echo "Running Job 1"
        stageVariable=2
        echo "##vso[task.setvariable variable=stageVariable]$stageVariable"

  - job: Job2
    displayName: "Job 2"
    condition: and(succeeded(), or(eq(variables['stageVariable'], 0), eq(variables['stageVariable'], 1), eq(variables['stageVariable'], 2)))  # Runs if stageVariable is 1 or 2
    steps:
    - script: |
        echo "Running Job 2"
        stageVariable=3
        echo "##vso[task.setvariable variable=stageVariable]$stageVariable"

  - job: Job3
    displayName: "Job 3"
    dependsOn: Job2
    condition: and(succeeded(), or(eq(variables['stageVariable'], 0), eq(variables['stageVariable'], 1), eq(variables['stageVariable'], 2), eq(variables['stageVariable'], 3)))  # Runs if stageVariable is 1, 2, or 3
    steps:
    - script: |
        echo "Running Job 3"
