stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar;isOutput=true]HelloWorld"
      name: SetVarStep

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    variables:
      myVarFromBuild: $[ dependencies.Build.outputs['BuildJob.SetVarStep.myVar'] ]
    steps:
    - script: |
        echo "The value of the variable is: $(myVarFromBuild)"
