trigger:
- main
pool: 
  vmImage: 'ubuntu-latest'

variables:
  - name: environment
    value: 'development' # Change this value to 'production' for production environment

  - name: ServiceAccount
    ${{ if eq(variables['environment'], 'development') }}:
      value: 'DevelopmentPool'
    ${{ if eq(variables['environment'], 'production') }}:
      value: 'ProductionPool'



steps:
- script: echo "Building in the $(environment) and $(ServiceAccount) environment using the $(poolName) pool."
