trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  var1: 10
  var2: 20

steps:
- script: |
    echo "Variable 1: $(var1)"
    echo "Variable 2: $(var2)"
    
    # Add the two variables
    var3=$(( $(var1) + $(var2) ))
    
    # Print the result
    echo "The result of addition is: $var3"
    
    # Set the result as an output variable
    echo "##vso[task.setvariable variable=var3]$var3"
  displayName: 'Add Variables and Print Result'

- script: |
    echo "The result stored in var3 is: $(var3)"
  displayName: 'Print the Third Variable'
