trigger: none

pool:
  vmImage: 'ubuntu-latest'
#variables:
#  resource_type: Kubernetes_Cluster
jobs:
- job: A
  steps:
  - script: |
      resource="Kubernetes_Cluster"
      echo "resource = $resource"
      echo "##vso[task.setVariable variable=resource_type;isOutput=true]$resource"
    displayName: "Print Resource Type"
    name: jobA
  # Your other steps here
- job: B
  dependsOn: A 
  variables:
    resource: $[ dependencies.A.outputs['resource'] ]
  steps:
  - script: |
      echo "Resource type is $(resource)"
      echo "Step 1"
    displayName: "Step 1"
    name: "step_1"
    condition: eq(variables['resource'], 'Kubernetes_Cluster')
  - script: |
      echo "Resource type is $(resource)"
      echo "Step 2"
    displayName: "Step 2"
    name: "step_2"
    condition: ne(variables['resource'], 'Kubernetes_Cluster')
