trigger: none

schedules:
- cron: "0 * * * *" # This cron expression schedules the pipeline to run at the top of every hour
  displayName: Hourly schedule
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  apiEndpoint: 'https://example.com/api/trigger'  # Replace with your actual endpoint
  payload: '{"param1": "value1", "param2": "value2"}'  # Replace with your actual payload

steps:
- task: InvokeRESTAPI@1
  displayName: 'Trigger Resource Provisioning Pipeline'
  inputs:
    method: 'POST'
    urlSuffix: ''
    serviceConnection: 'your_service_connection'  # Replace with the name of your service connection
    headers: |
      Content-Type: application/json
      Authorization: Basic $(echo -n ":$(PAT_TOKEN)" | base64)
    body: '$(payload)'
  env:
    API_ENDPOINT: $(apiEndpoint)


