trigger:
- main

variables:
  status_passed: 0

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - script: |
        echo "##vso[task.setvariable variable=status_passed]$((status_passed + 1))"
        echo "Stage 1: status_passed=$(status_passed)"
      displayName: 'Increment and print status_passed in Stage 1'

- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: Job2
    steps:
    - script: |
        echo "##vso[task.setvariable variable=status_passed]$((status_passed + 1))"
        echo "Stage 2: status_passed=$(status_passed)"
      displayName: 'Increment and print status_passed in Stage 2'

- stage: Stage3
  dependsOn: Stage2
  jobs:
  - job: Job3
    steps:
    - script: |
        echo "##vso[task.setvariable variable=status_passed]$((status_passed + 1))"
        echo "Stage 3: status_passed=$(status_passed)"
      displayName: 'Increment and print status_passed in Stage 3'
