trigger: none


pool:
  vmImage: 'ubuntu-latest'

variables:
  resource_type: Kubernetes_Cluster

jobs:
- job: MyJob
  steps:
  - script: echo "Resource type is $(resource_type)"
    displayName: "Print Resource Type"
  # Your other steps here

- job: B
  condition: eq(variables['resource_type'], 'Kubernetes_Cluster')
  steps:
  - script: |
      echo "Step 2.1"
    displayName: "Step 2.1"
  - script: |
      echo "Step 2.2"
    displayName: "Step 2.2"

