stages:
  - stage: stage_deploy
    displayName: Production
    jobs:
      - job: job_deploy_infrastructure
        displayName: Deploy Some Infrastructure
        steps:
          - bash: |
              SOMEVALUE="bleh"
              echo "##vso[task.setvariable variable=someName;isOutput=true;]Kubernetes_Cluster"
              echo "variable value is $(someName)"
      - job: job_deploy_code
        displayName: Deploy Some Code
        dependsOn: ['job_deploy_infrastructure']
        variables:
          someName: $[ dependencies.job_deploy_infrastructure.outputs['setVariable.someName'] ]
        steps:
          - bash: |
              echo "the variable value is $(someName)"
