
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureDevOpsOrg: 'your_organization'
  projectName: 'your_project'
  pipelineId: 'target_pipeline_id' # ID of the pipeline you want to monitor
  sleepTime: 300 # Time to sleep in seconds (5 minutes)

steps:
- script: |
    echo "Checking the status of the pipeline every 5 minutes..."
    while true; do
      echo "Fetching the latest run status of pipeline ID: $(pipelineId)"
      response=$(curl -s \
        -u ":$(System.AccessToken)" \
        -H "Content-Type: application/json" \
        "https://dev.azure.com/$(azureDevOpsOrg)/$(projectName)/_apis/pipelines/$(pipelineId)/runs?api-version=6.0")

      latestRunStatus=$(echo $response | jq -r '.value[0].state')
      echo "Latest run status: $latestRunStatus"

      if [[ "$latestRunStatus" == "completed" ]]; then
        echo "The pipeline run has completed."
        break
      else
        echo "The pipeline run is still in progress. Sleeping for $(sleepTime) seconds."
        sleep $(sleepTime)
      fi
    done
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: "Check Pipeline Status"
