
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureDevOpsOrg: 'your_organization'
  projectName: 'your_project'
  pipelineId: 'target_pipeline_id' # ID of the pipeline you want to monitor
  sleepTime: 300 # Time to sleep in seconds (5 minutes)

steps:
- script: |
    echo "Checking the status of the pipeline every 5 minutes..."
    while true; do
==========

trigger:
- main

stages:
- stage: Stage1
  jobs:
  - job: JobA
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "##vso[task.setvariable variable=myVar;isOutput=true]Hello from Stage1 JobA"
      name: SetOutputVar

- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: JobB
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      myVarFromStage1: $[ dependencies.Stage1.outputs['JobA.SetOutputVar.myVar'] ]
    steps:
    - script: |
        echo "The value of the variable from Stage1 JobA is: $(myVarFromStage1)"
      displayName: 'Print Variable from Stage1 JobA'
