trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Job1
  displayName: 'Job 1 - Set and print a variable'
  steps:
  - script: |
      echo "##vso[task.setvariable variable=myVar;isOutput=true]Hello from Job 1"
      echo "Job 1 completed"
    name: SetVariable

- job: Job2
  displayName: 'Job 2 - Print the variable from Job 1'
  dependsOn: Job1
  variables:
    myVarFromJob1: $[ dependencies.Job1.outputs['SetVariable.myVar'] ]
  steps:
  - script: |
      echo "Variable from Job 1: $(myVarFromJob1)"
      echo "Job 2 completed"
